name: wechat
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_webview_plugin: ^0.2.1+2
  date_format: ^1.0.4
  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - images/loading.png

  - images/home.png
  - images/homecheck.png
  - images/contact.png
  - images/contactcheck.png
  - images/find.png
  - images/findcheck.png
  - images/profile.png
  - images/profilecheck.png
  - images/new.png
  - images/group.png
  - images/public.png
  - images/head.jpg
